import { Button } from '@/components/ui/button'
import React from 'react'
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
  {
    question: "How does the Match Score work?",
    answer:
      "Our system analyzes your resume and compares it to job descriptions using AI. The match score tells you how well your profile aligns with a job role."
  },
  {
    question: "Can I edit the AI-generated resume?",
    answer:
      "Yes! You can fully customize the resume generated by our AI. Change content, layout, or add/remove sections as per your needs."
  },
  {
    question: "Is this platform free to use?",
    answer:
      "Yes, the basic features like resume builder and job recommendations are free. Premium features may be introduced later."
  },
  {
    question: "How accurate are job recommendations?",
    answer:
      "Our recommendations are powered by AI and improve over time as you interact with the platform and provide preferences."
  },
  {
    question: "Is my personal data safe?",
    answer:
      "Absolutely. We use secure, encrypted storage and do not share your personal data with any third parties without your consent."
  }
];


export const FAQ = () => {
  return (
    <section className="container text-left py-16">
  <h2 className="font-medium mb-4">
    Frequently Asked Questions
  </h2>
  <p className="text-gray-600 mb-6 text-base md:text-lg">
    Got questions about how our platform works? Here are answers to help you get started with AI Resume Builder, Match Score, and more.
  </p>
  <Accordion type="single" collapsible>
    {
        faqs.map(({ question, answer }) => {
            return (
                <AccordionItem key={question} value={question}>
                    <AccordionTrigger className='text-base md:text-lg cursor-pointer'>{question}</AccordionTrigger>
                        <AccordionContent>
                            <p className='text-sm md:text-base '>{answer}</p>
                        </AccordionContent>
                </AccordionItem>
            )
        })
    }
</Accordion>
</section>
  )
}
